services:
  # Postgres Database Service
  pg-database:
    image: postgres:18
    container_name: pg-database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgres
    ports:
      - "5432:5432"
    # No need to specify network here since all containers in the same docker-compose file share the same default network

  # Data Ingestion Service
  ingest-data:
    image: taxi_ingest:1.0.0
    # Build the custom image from the Dockerfile in the current directory
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ingest-data
    # This ensures the "pg-database" container is started before this one
    depends_on:
      - pg-database
    command: >   # With '>' we can stack commands vertically
      --pg_username=root 
      --pg_password=root
      --pg_host=pg-database
      --pg_port=5432
      --pg_db=ny_taxi

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"

# Define the named volumes for data persistence
volumes:
  ny_taxi_postgres_data:
  pgadmin_data: