services:
  pg-database:
    image: postgres:18
    container_name: pg-database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgres
    ports:
      - "5432:5432"

  ingest-data:
    image: taxi_ingest_green:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ingest-data
    depends_on:
      - pg-database
    command: >
      --pg_username=root
      --pg_password=root
      --pg_host=pg-database
      --pg_port=5432
      --pg_db=ny_taxi

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: